metar_server/metar_server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('metarapp/', include('metarapp.urls'))
]

metar_server/metarapp/urls.py
from django.urls import path
from . import views

app_name = 'metarapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
]

metar_server/metarapp/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator


class Metar(models.Model):
    RAW_TEXT_RE = r'\A([A-Z]([A-Z]|[0-9]){2,3} [0-3])'
    STATION_ID_RE = r'[A-Z]([A-Z]|[0-9]){2,3}'
    WX_STRING_RE = r'\A[-\+]?[A-Z]{2,10}'
    METAR = 'METAR'
    SPECI = 'SPECI'
    METAR_TYPE_CHOICES = [
        (METAR, 'METAR'),
        (SPECI, 'SPECI')
    ]
    raw_text = models.TextField(
        validators=[RegexValidator(RAW_TEXT_RE)]
    )
    station_id = models.CharField(
        max_length=4,
        validators=[RegexValidator(STATION_ID_RE)]
    )
    observation_time = models.DateTimeField()
    temp_c = models.FloatField(
        validators=[
            MaxValueValidator(70),
            MinValueValidator(-60)
        ]
    )
    dewpoint_c = models.FloatField(
        validators=[
            MaxValueValidator(70),
            MinValueValidator(-60)
        ]
    )
    wind_dir_degrees = models.PositiveSmallIntegerField(
        default=360,
        validators=[MaxValueValidator(360)]
    )
    wind_speed_kt = models.PositiveSmallIntegerField(
        default=0,
        validators=[MaxValueValidator(150)]
    )
    wind_gust_kt = models.PositiveSmallIntegerField(
        blank=True,
        null=True,
        validators=[MaxValueValidator(150)]
    )
    visibility_m = models.PositiveSmallIntegerField(
        default=9999,
        validators=[MaxValueValidator(9999)]
    )
    altim_in_hg = models.FloatField(
        validators=[
            MaxValueValidator(32.5),
            MinValueValidator(25.1)
        ]
    )
    wx_string = models.CharField(
        blank=True,
        max_length=16,
        validators=[RegexValidator(WX_STRING_RE)]
    )
    cloud_ceiling = models.PositiveIntegerField(
        blank=True,
        null=True
    )
    vert_vis_ft = models.PositiveSmallIntegerField(
        blank=True,
        null=True
    )
    metar_type = models.CharField(
        choices=METAR_TYPE_CHOICES,
        default=METAR,
        max_length=5
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['station_id', 'observation_time'],
                name='unique_metar'
            )
        ]


class Airport(models.Model):
    STATION_ID_RE = r'[A-Z]([A-Z]|[0-9]){2,3}'
    station_id = models.CharField(
        max_length=4,
        validators=[RegexValidator(STATION_ID_RE)]
    )
    register_date = models.DateField()
    is_fetched = models.BooleanField()

metar_server/metarapp/forms.py
from __future__ import annotations
import re
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import Metar


class MyLoginForm(AuthenticationForm):
    def __init__(self, request, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class MetarAppForm(forms.Form):
    icao = forms.CharField(
        label='空港コード（RJ__）',
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    search_date = forms.DateTimeField(
        input_formats=[r'%Y-%m-%d'],
        label='日付',
        widget=forms.DateTimeInput(
            attrs={'class': 'form-control flatpickr'}
        )
    )
    metar_order = forms.ChoiceField(
        label='METAR並び順（時間）',
        choices=[
            ('asc', '昇順'),
            ('desc', '降順')
        ],
        widget=forms.RadioSelect()
    )

    def clean(self) -> dict[str, any]:
        cleaned_data = super().clean()
        cleaned_icao = cleaned_data.get('icao')
        if not re.search(Metar.STATION_ID_RE, cleaned_icao):
            raise forms.ValidationError('ICAO ID "RJ__"を入力してください')
        cleaned_search_date = cleaned_data.get('search_date')
        if not cleaned_search_date:
            raise forms.ValidationError('日付を入力してください')
        return cleaned_data


class GetMetarNowForm(forms.Form):
    airport = forms.MultipleChoiceField(
        label='Choose airport',
        choices=[],
        widget=forms.SelectMultiple(attrs={'size': 5, 'id': 'airport_select'})
    )

    def __init__(self, airport_list: list[str], *args, **kwargs) -> None:
        """Add airports to choices of this form.

        Other arguments are for super().__init__()

        Args:
            airport_list (list[str]): airport list from Airport model.
        """
        super().__init__(*args, **kwargs)
        self.fields['airport'].choices = [(id, id) for id in airport_list]

metar_server/metarapp/views.py
import csv
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, logout_then_login
from django.http import HttpRequest, HttpResponse
from django.db.models.query import QuerySet
from datetime import timedelta
from .forms import MyLoginForm, MetarAppForm
from .models import Metar


@login_required(login_url='/metarapp/login')
def index(request: HttpRequest):
    params = {
        'user_name': request.user.username,
        'icao': '',
        'getdate': '',
        'form': MetarAppForm(),
        'outmetar': ''
    }
    if (request.method == 'POST'):
        form_post = MetarAppForm(request.POST)
        if not form_post.is_valid():
            params['form'] = form_post
            return render(request, 'metarapp/index.html', params)
        # POST data is "YYYY-MM-DD" format (no time string).
        # Therefore, time of start_datetime is 0:00 (local timezone).
        start_datetime = form_post.cleaned_data['search_date']
        end_datetime = start_datetime + timedelta(hours=23, minutes=59)
        params['icao'] = request.POST['icao']
        params['getdate'] = request.POST['search_date']
        params['form'] = form_post
        metar_return = Metar.objects \
            .filter(
                station_id=request.POST['icao'],
                observation_time__range=(start_datetime, end_datetime),
            ) \
            .order_by('observation_time')
        if request.POST['metar_order'] == 'desc':
            params['outmetar'] = metar_return.reverse()
        else:
            params['outmetar'] = metar_return

        if 'submit_csv' in request.POST:
            return _create_csv_response(metar_return)
    return render(request, 'metarapp/index.html', params)


def logout(request):
    return logout_then_login(request=request, login_url='/metarapp/login')


class Login(LoginView):
    form_class = MyLoginForm
    template_name = 'metarapp/login.html'


def _create_csv_response(query: QuerySet) -> HttpResponse:
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="metar.csv"'
    writer = csv.writer(response)
    field_names = list(query.values()[0].keys())[1:]
    writer.writerow(field_names)
    for record in query.values_list():
        writer.writerow(list(record)[1:])
    return response

metar_server/metarapp/templates/metarapp/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block head_title %}{% endblock %}</title>
    <!-- Bootstrap: CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" 
    crossorigin="anonymous">
    {% block head_link %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand ms-3" href="{% url 'metarapp:index' %}">過去METAR検索</a>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav me-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-item nav-link" href="{% url 'metarapp:logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li>
            <a class="nav-item nav-link" href="{% url 'metarapp:login' %}">ログイン</a>
          </li>
          {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="navbar-text pe-3">
            ログインユーザー：{{user_name}}
          </li>
        </ul>
        {% endif %}
      </div>
    </nav>

    <div class="container mt-3" style="padding-top: 3em;">
      {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap: JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" 
    crossorigin="anonymous"></script>
    {% block body_script %}{% endblock %}

  </body>
</html>

metar_server/metarapp/templates/metarapp/index.html
{% extends "metarapp/base.html" %}
{% block head_title %}
過去METAR検索
{% endblock %}

{% block head_link %}
<!-- flatpickr: lightweight, powerful javascript datetimepicker with no dependencies  -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock %}

{% block content %}
<h1>過去METAR検索</h1>
<h2>入力</h2>
<p>
  表示したいMETARの空港コード＆日付を入れてください。<br>
  日本時間の一日分のMETARが表示されます。
</p>
<form action="{% url 'metarapp:index' %}" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td></td>
      <td>
        <input class="btn btn-primary" type="submit" 
        name="submit_display" value="検索実行">
      </td>
      <td>
        <input class="btn btn-secondary" type="submit" 
        name="submit_csv" value="CSVファイルでダウンロード">
      </td>
    </tr>
  </table>
</form>
  
<h2>出力</h2>
<p>選択された空港と日付：</p>
<p>{{icao}}<br>{{getdate}}</p>
<table class="table font-monospace">
  {% for item in outmetar %}
    <tr><td>{{item.raw_text}}</td></tr>
  {% endfor %}
</table>
{% endblock %}

{% block body_script %}
<!-- flatpickr -->
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
  window.addEventListener("DOMContentLoaded", function() {
    flatpickr(".flatpickr", {
      enableTime: false
    });
  });
</script>
{% endblock %}

metar_server/metarapp/templates/metarapp/login.html
{% extends "metarapp/base.html" %}
{% block head_title %}
過去METAR検索
{% endblock %}

{% block content %}
<h1 class="text-center">ログイン</h1>
<form action="" method="POST">
  {% csrf_token %}
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-body">
        {{ form.non_field_errors }}
        {% for field in form %}
          {{ field }}
          {{ field.errors }}
          <hr>
        {% endfor %}
        <input class="btn btn-success btn-lg btn-block" type="submit" value="ログイン">
      </div>
    </div>
  </div>
</form>
{% endblock %}